### PR TITLE
Ubuntu22 Zephyr image

### PR DESCRIPTION
**Pull request by dnltz**

### CODE REVIEW

**Comment by dnltz** [comment]
@smk-embedded yeah adding the SDK version between zephyr and ubuntu is not a bad idea...

**Comment by jonas-rem** [comment]
I reference the official CI containers from the Zephyrproject at https://hub.docker.com/r/zephyrprojectrtos/ci/tags. That allows to reference tagged versions for fixed SDK versions. For projects where I actively develop I use Zephyr main branch and the latest CI image if possible. But that solution is not really efficient as the containers have to be downloaded with each CI run. For example see https://github.com/phytec/zephyr-ksp0714/blob/9ad0460ebbd4252eb6f4af52b4133ffaf8881033/.github/workflows/build.yml#L9

Is it possible to cache the official containers from the zephyrproject locally? Like cache automatically and delete if not in use for 3 weeks.

For your current approach:
- You could install the SDK only for required architectures (arm, risc-V?) for each run, which will reduce the download size and installation time.
- But the SDK version may not be the only issue, python packages can be required in different versions for different versions of Zepyhr as well.

**Comment by dnltz** [comment]
@smk-embedded @jonas-rem okay, so now we have just a zephyr-ubuntu image with all host packages installed and a zephyr-0.16.y-ubuntu image (which fetches 16.6 now). All SDK minor releases should be handles via image tags.

The zephyr-ubuntu image could be used to manually download a SDK or use a local SDK.

**Comment by jonas-rem** [comment]
>  Just run this github action on a self-hosted system and it will cache docker images locally.

@dnltz did you referred to a link to a specific github action?

If the images can be cached easily/automatically, why not just use the existing images from zephyrproject? I understand it may give us more flexibility to use our own containers in case we have to customize anything. Are there other advantages these custom container configs offer for us?

**Review by jonas-rem — APPROVED** [review]

**Pull request merged**
